FROM golang:1.24 AS builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 go build -o bin/byb cmd/server/main.go . && \
    go clean -cache -modcache -i -r && \
    rm -rf /go/pkg /go/src

FROM alpine:3.21
WORKDIR /root/
COPY --from=builder /app/bin/byb .
RUN chmod +x /root/byb && \
    mkdir /root/logs
CMD [ "./byb" ]