name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile.prod --tag byb-backend:$(date +%s)

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_id }}
        files: |
          ./byb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      run: |
        docker run --rm byb-backend:latest cp /root/byb ./byb
        gh release upload v1.0.${{ github.run_id }} ./byb --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
