name: Deploy Go App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
    
    - name: Deploy no Servidor
      run: |
        ssh deploy@${{ secrets.SERVER_IP }} << 'EOF'
        cd ~
        if [ ! -d "backend/.git" ]; then
          git clone git@github.com:bybhub/backend.git
        fi
        cd backend
        git pull origin main
        go build cmd/server/main.go -o main
        sudo systemctl restart backend
        EOF
