name: Prevent Direct Pushes to Main
on: push
jobs:
  block-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check if push is direct to main
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "Direct pushes to main are not allowed!"
            exit 1
          fi
